### ISSUE TITLE
Installation of extruder onto x-carriage is difficult due to missing zip ties

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/bear_extruder_and_x_axis#1]
This is something I am working on it, I would like to try to split the x-carriage-back into to two pieces. Not sure it will be possible.

**Comment by albegouws** [comment]
What about a temporary install helper just using the top two screws that hold the top bearings together?

**Comment by gregsaun** [comment]
yes this is another possibility in case I cannot make the back in two parts

**Comment by gregsaun** [comment]
Solved with release 0.40-alpha
