### ISSUE TITLE
 bear_extruder_and_x_axis/printed_parts/stl/common/extruder_body.stl needs a 4mm brim

### ISSUE THREAD

**Issue by MikeRatcliffe** [gregsaun/bear_extruder_and_x_axis#12]
Not a true issue but the following part needs a 4mm brim to print:

`bear_extruder_and_x_axis/printed_parts/stl/common/extruder_body.stl`

Otherwise the bit indicated in the picture has a tendency to fall over during printing.

<img width="610" alt="needs brim" src="https://user-images.githubusercontent.com/116941/45255271-f8200f00-b37b-11e8-906b-534991fa2a70.png">

**Comment by gregsaun** [comment]
Next release will use a zip tie, like this you can replace pinda or nozzle fan without disassembling the body :-)
