### ISSUE TITLE
Assembly guide specifies 20T toothed idler but BOM specifies 16T toothed idler

### ISSUE THREAD

**Issue by matthew-humphrey** [gregsaun/bear_extruder_and_x_axis#16]
![bear_idler_doc_issue](https://user-images.githubusercontent.com/5487637/45917643-bab58a00-be2f-11e8-9956-073f8670960a.png)

**Comment by gregsaun** [comment]
20T idler is not released yet, only available in dev branch. But will be released tomorrow if everything is going well ;-)

**Comment by matthew-humphrey** [comment]
Yes, I know, I am working off the dev branch and just wanted to make sure you saw this typo.
