### ISSUE TITLE
Centered mounting hole to hold X carriage and exturder body is off by 0.2mm

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/bear_extruder_and_x_axis#17]

**Comment by trevjonez** [comment]
which parts does this effect? printing the mk3 carriage and x ends now and plan to do the body chunks tomorrow after this plate finishes

**Comment by gregsaun** [comment]
You can go for it, the difference is very small. If really you have trouble to assemble it better to use a file than reprinting the part.

Here is a view of the issue :
![bear_extruder_issue_17](https://user-images.githubusercontent.com/12335098/46458601-a02bcb00-c7b6-11e8-8b20-52992846d565.jpg)
