### ISSUE TITLE
Unable to remove filament from bowden cover when filament sensor kick it because it is the end of the filament

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/bear_extruder_and_x_axis#21]
Filament sensor needs to be disassembled.

https://www.facebook.com/groups/prusabearupgrade/permalink/1105132772980365/

**Comment by trevjonez** [comment]
so can I tag on another chore to this one? the sensor cover screw arrangement is just slightly different than the stock arrangement. as I was trying out the JLTX interposer yesterday I could only use one screw to attach it and still have the filament path line up.

**Comment by gregsaun** [comment]
@trevjonez screw are going to be totally different on the next version unfortunately

**Comment by gregsaun** [comment]
fixed in release 0.6.0-alpha
