### ISSUE TITLE
MK2(s) compatibility state?

### ISSUE THREAD

**Issue by BenRoe** [gregsaun/bear_extruder_and_x_axis#23]
Hello,
i did the bear upgrade and updated my MK2S to MK2.5.
Now i build a MK2S with the left frame/parts.
Can i use this extrude/x-axis parts for a MK2S build (without filament sensor and old pinda)?

**Comment by mattiras** [comment]
Hi @BenRoe 

Are you still building Bear MK2? It is possible to get Bear X-axis work on MK2. I have modified the probe offset on 2.3.2 firmware and It works without issues.

https://github.com/mattiras/Prusa-MK2-Firmware-for-bear-x-axis

If you like. Try it to confim. (at your own risk). Are you able to compile?

**Comment by gregsaun** [comment]
@mattiras Nice!
