### ISSUE TITLE
Misplaced air-nozzle mounting holes

### ISSUE THREAD

**Issue by RH-Dreambox** [gregsaun/bear_extruder_and_x_axis#24]
Hi Gregsaun,
I work with a new air-nozzle that will fit your extruder.
But when I assemble the extruder I see that some holes need to be moved, this in order to maintain full compatibility with the original extruder.

At the attached drawing you will see what needs to be done. In addition, I would like a little support for the right side of the air nozzle (see drawing).

![move holes](https://user-images.githubusercontent.com/35836981/50397782-efa8e400-0772-11e9-805e-f4256763b732.png)

**Comment by gregsaun** [comment]
I close this one as we are going to tackle this wit the #20 issue .
