### ISSUE TITLE
x-carriage compatibility with new bondtech extruder

### ISSUE THREAD

**Issue by joeycerone** [gregsaun/bear_extruder_and_x_axis#26]
Hi Greg,
Wondering if the current x-carriage and x-end parts are compatible with the newly released bondtech extruder upgrade for the mk3? I have one on order and was planning on upgrading to your parts if they are compatible. If not, do you plan on updating them in the near future? Thanks.

**Comment by gregsaun** [comment]
Hi Joey, as you may probably know, the Bondtech carriage is available here :
https://github.com/gregsaun/bear_extruder_and_x_axis/tree/master/optional_parts/bondtech_x_carriage
