### ISSUE TITLE
x_carriage_back.f3d file

### ISSUE THREAD

**Issue by gorillamotors** [gregsaun/bear_extruder_and_x_axis#34]
I am building a Bondtech BMG-M Extruder / Mosquito magnum hotend to my Prusa MK3. I am also adding some Igus RJZM-01-08 bearings. The problem is that the bearings are 16mm x 25.25mm and the Bear parts are 15.3mm x 24mm and the bearings don't fit. Could you please attach the x_carriage_back.f3d file to this file so that I can modify the file.

**Comment by gregsaun** [comment]
Hi, sorry for my late answer, the Fusion 360 sources are all available here:
https://github.com/gregsaun/bear_extruder_and_x_axis/tree/master/src

Or in optional part like for the Bondtech X carriage:
https://github.com/gregsaun/bear_extruder_and_x_axis/tree/master/optional_parts/bondtech_x_carriage
