### ISSUE TITLE
BMG-M

### ISSUE THREAD

**Issue by bpvarsity** [gregsaun/bear_extruder_and_x_axis#35]
Is there a way to mount the new BMG-M that was released for the slice mosquito with this setup?

**Comment by gregsaun** [comment]
Are you talking about this one?
https://www.bondtech.se/en/product/bmg-m-extruder/

**Comment by bpvarsity** [comment]
Yes

**Comment by gregsaun** [comment]
I have not seen this being compatible with Prusa printers sorry, do you have a link?

**Comment by bpvarsity** [comment]
Ah just heard from bontech they have one coming out for prusa soon. It's in beta testing so that will be be great. Should work and mount like the other BMG upgrade kit for prusa printers you support
