### ISSUE TITLE
MK3 version?

### ISSUE THREAD

**Issue by jokeane** [gregsaun/bear_extruder_and_x_axis#37]
Hi, I see now with the latest version it only shows MK3S? Does this also work with a MK3?
I printed and built an earlier version and installed it on my MK3, and it works fine, but I'm curious about compatibility of this latest version of the parts. Thanks!

**Comment by gregsaun** [comment]
Works totally fine except that you can't use the laser filament sensor. You can use the stock firmware as well with this one.
