### ISSUE TITLE
Cable guide back a - difficult print

### ISSUE THREAD

**Issue by albegouws** [gregsaun/bear_extruder_and_x_axis#4]
Printing the parts right now, the a part of the cable guide in the default orientation is a very difficult print to do successfully, the initial two or so layers are only time little marks on the bed, after a few layers it comes loose - depending on speed obviously. You can rotate and print at an angle but I think the one side could be flattened to print easier? 

Will let you know how the rest goes, MK3 and Mk2.5 running at full speed.

**Comment by gregsaun** [comment]
Cable guide back a and b need to be printed with other parts because they are very small. However I think I can use another orientation, I'll give a try ;-)

**Comment by albegouws** [comment]
I flipped it on the flat side and adjusted angle to 5 degrees.

________________________________

**Comment by gregsaun** [comment]
Hello, I did see that my parts was really not correctly aligned and I was thinking that you were asking another orientation. Sorry for the inconveniences!

I am going to fix it now and make it just a bit wider too

**Comment by gregsaun** [comment]
Done! Thanks for the help
