### ISSUE TITLE
Compatability for linear guideways

### ISSUE THREAD

**Issue by nikhil8333** [gregsaun/bear_extruder_and_x_axis#41]
hi, I am trying to make my own design of printer, and tried to accommodate it on the the linear guide-way of hgh15 please help me with, I don't want you to create a X carriage for my use case, but to create a back plate that can be fitted to any X carriage making it universal. hopping you would help me, thanks in advance

**Comment by gregsaun** [comment]
Hello, I would love to have time to help you on such a cool project but unfortunately it is not possible anymore today.

I am planning to rework in depth the X axis but we have to finish few ongoing project at the moment (like the Y axis linear rail).

**Comment by nikhil8333** [comment]
Well that's sad to hear, but now I am trying with some bull gear model inspiration and will put it on GitHub soon, love to work alongside with you, ping when you get time

**Comment by gregsaun** [comment]
What is bull gear model?
