### ISSUE TITLE
Filament sensor is always triggered

### ISSUE THREAD

**Issue by Sjoerrdd** [gregsaun/bear_extruder_and_x_axis#42]
Hi,
My filament sensor is always triggered, only if I put it out of the extruder it returns 'OPEN' (M119 command).

**Comment by gregsaun** [comment]
May I ask you to share a pic with sensor close and sensor open? This might save some words ;-)

Which printer do you run? MK2.5S or MK3S?

**Comment by Sjoerrdd** [comment]
I'm using the MK3S extruder, I'll send a picture when I'm home. (± 5 hours from now)

**Comment by Sjoerrdd** [comment]
![20191213_152049](https://user-images.githubusercontent.com/19862992/70806843-7dcf0d80-1dbc-11ea-98d7-5045005cf114.jpg)
![20191213_152101](https://user-images.githubusercontent.com/19862992/70806854-8293c180-1dbc-11ea-9ebc-60fb9613e598.jpg)

**Comment by gregsaun** [comment]
Thank you for your image. I see several issues on your extruder. Could you give me more precision about those points?

- Blue arrow: the carriage is not aligned with extruder body. This could bend the connector and so the sensor PCB making the reading difficult.
- Green arrow: sounds like there is a crack or opening here, make sure not light enters here
- Yellow arrow: not linked to the filament sensor but you are using a pancake stepper which will have not enough torque and loose steps.
![sjoerrdd_filament_sensor_issue_01](https://user-images.githubusercontent.com/12335098/70862585-88191500-1f3e-11ea-8dd6-aca6d26ad35c.jpg)

**Comment by Sjoerrdd** [comment]
Thanks,
* That's right, I solved that by printing a new carriage, thanks :)
* It isn't a crack, it's a failed layer (I don't have enough PETG to reprint it), when my new roll arrives, I'll fix it
* Pancake stepper motor is temporarily, the new one will arrive later this week. (the original broke :( )

**Comment by gregsaun** [comment]
When no filament is inserted you have the opening here that looks too big. Could you find why?
![sjoerrdd_filament_sensor_issue_01](https://user-images.githubusercontent.com/12335098/70863111-02e52e80-1f45-11ea-8c17-54a445440ec4.jpg)

**Comment by gregsaun** [comment]
Also could you try the filament sensor out of the body?

**Comment by Sjoerrdd** [comment]
It worked, there were some "pustules" on the back of the lever, so it was pushed too far forward.

Thanks for helping :)

**Comment by gregsaun** [comment]
Great!
