### ISSUE TITLE
Bondtech Mosquito X-Carriage and X-Carriage Back MK3S

### ISSUE THREAD

**Issue by ctilley83** [gregsaun/bear_extruder_and_x_axis#43]
Something to check.  For the lower single bearing, the X Carriage back is not clamping against the bearing.  This results in significant slop. I'm using the Bondtech mosquito X carriage in optional parts, with the x carriage back in the mk3s printed parts in the dev branch.  Maybe I'm mismatching by mistake?

**Comment by gregsaun** [comment]
I double checked my files and this is not an issue, it should clamp correctly.

Could you check that the bottom of the X carriage isn't broken and that you are using M3x10mm screws (sometimes people are confusing with M3x12mm screws)?
