### ISSUE TITLE
Step file request

### ISSUE THREAD

**Issue by ChipTechno** [gregsaun/bear_extruder_and_x_axis#45]
Hi Greg,
I known that you already make the fusion360 source files available, but the computer I'm using is unable to use fusion 360 due to weak CPU and lack of graphic card. Can you release the step file of the design in dev branch too?
Thank you!

**Comment by gregsaun** [comment]
Will do on the next release. It is really a pain to do it in Fusion 360 so I wanted to do that for final release but it takes time as you can see :-D
