### ISSUE TITLE
Which material to use?

### ISSUE THREAD

**Issue by St0RM53** [gregsaun/bear_extruder_and_x_axis#46]
Regarding printing nozzle_fan_duct i have the following materials:
- Prusament PLA/PETG/ASA
- EasyABS
- CPE HG100
- ColorFabb XT-CF20

Which one you recommend using?

Kind regards

**Comment by trevjonez** [comment]
The stock prusa fan nozzle is ASA. I would expect the ASA, ABS, CPE HG100 and XT-CF20 to all perform well for the part. The ABS is likely the most cost effective solution.

**Comment by gregsaun** [comment]
Yes I would go ASA probably. I am personally using Extrudr GreenTec Pro but it is expensive (but no styrene and biodegradable). If you never tried annealing HTPLA I would avoid trying that on the shroud, need a bit of experience I think.

**Comment by St0RM53** [comment]
Thanks i ended up printing it in ASA successfully :)
