### ISSUE TITLE
Hemera fan knocks on the x-motor-end

### ISSUE THREAD

**Issue by knickohr** [gregsaun/bear_extruder_and_x_axis#47]
I build up my new Bear 2.1 with the BEARmera. There is maybe a little problem with the dimensions of some parts. The Hemera fan knocks on the x-motor-end while going left to the startup position. So, until there is no endstop switch (MK3s) the fan drives into the left side. On the second picture you see, there is some space left between the x-motor-end and the x- carriage.

Thomas

![IMG_0184](https://user-images.githubusercontent.com/63048210/78247995-1f08dd80-74ec-11ea-9d25-e9ab27d1faec.JPG)
![IMG_0185](https://user-images.githubusercontent.com/63048210/78248011-25975500-74ec-11ea-9249-c9c8c53cd09c.JPG)
![IMG_0186](https://user-images.githubusercontent.com/63048210/78248028-2a5c0900-74ec-11ea-8178-6407410fc878.JPG)

**Comment by gregsaun** [comment]
It is because you are using the old X ends, you need to use the new ones from the dev branch.

**Comment by knickohr** [comment]
Really ?  I'm sure I've use the ones from the dev.

**Comment by knickohr** [comment]
Ahhh, OK. I see. So I also used the wrong x end idler and the x carriage ?

**Comment by gregsaun** [comment]
Not that I see. Sorry, should be easier soon as everything will be available from the github.

**Comment by knickohr** [comment]
x carriage back is different too, x carriage and x end idler are OK. Seems I mixed parts. Or I used an earlier dev version ?

**Comment by gregsaun** [comment]
No it was available at the same time as the BearMera files. You have to get the X ends, X carriage back and cable guide back from the dev branch.

**Comment by knickohr** [comment]
OK, all the parts with date "2 months ago".

**Comment by gregsaun** [comment]
This is correct, if you check the X end motor for example you will see that the shape of the arm is different than yours.

**Comment by knickohr** [comment]
Fixed ! :-)
![IMG_2142](https://user-images.githubusercontent.com/63048210/78507824-bedf9900-7782-11ea-8f36-52bbbf7a7ae4.JPG)
