### ISSUE TITLE
Extruder cover - print needs supports

### ISSUE THREAD

**Issue by albegouws** [gregsaun/bear_extruder_and_x_axis#5]
This bit needs supports or maybe rethinked angle here:

![extruder_cover_overhang](https://user-images.githubusercontent.com/29041479/40269603-006ee404-5b81-11e8-93f8-3cf1db91591d.PNG)

**Comment by gregsaun** [comment]
If you check the STL there is a small support that comes with the part, you need to break it after the print.

In Fusion 360, if you check the bodies of this part you will see that their is two, one is hidden for "esthetic" but I unhidden it when generating the STL
