### ISSUE TITLE
MK3S+ support?

### ISSUE THREAD

**Issue by tfendt** [gregsaun/bear_extruder_and_x_axis#56]
Does the current set of models support the MK3S+? All of my printers (MK3S) are currently using the bear extruder and x-axis. What (if anything) would I need to change if I ordered the '+' upgrade from Prusa?

**Comment by gregsaun** [comment]
Yes it is compatible with MK3S+. I will update the documentation soon to add this info.

**Comment by gregsaun** [comment]
No changes are need as it is only the SuperPinda that has been added to the extruder.

**Comment by tfendt** [comment]
Thanks!
