### ISSUE TITLE
mk8 extruder how to mount mk3s?

### ISSUE THREAD

**Issue by easonjim** [gregsaun/bear_extruder_and_x_axis#57]
Dear, 
     mk8 extruder how to mount mk3s? BearMera extruder is E3D Hemera mount, can you make it to mk8? thanks.

**Comment by gregsaun** [comment]
Hi, it is quite some work to adapt it and support it, I am not planning to do it for now sorry.

**Comment by easonjim** [comment]
thanks, i change my idea, switch e3d v6 now.
