### ISSUE TITLE
x-axis for original extruder

### ISSUE THREAD

**Issue by easonjim** [gregsaun/bear_extruder_and_x_axis#61]
Dear gregsaun,
When I used the parts on the left and right ends of the x-axis of the bear in the original mk3s, I found that the original extruder would jam the bottom belt. Is it incompatible with the original extruder parts?
thanks.

**Comment by gregsaun** [comment]
Hello, correct, the original extruder is not compatible with the Bear X axis. I have several improvements on the belt path as well as the addition of the tensioner and all this is breaking the compatibility. You can find more information about compatibility here:
https://github.com/gregsaun/bear_extruder_and_x_axis#compatibility
