### ISSUE TITLE
PINDA mount is 1.5mm too close to X smooth rods

### ISSUE THREAD

**Issue by gregsaun** [gregsaun/bear_extruder_and_x_axis#7]
Because the X carriage is thinner by 1.5mm, the PINDA is closer to X smooth rods by the same dimension.

**Comment by Panayiotis-git** [comment]
My measurements are not perfect (design imported to Tinkercad...), but related to the original design, I measure:
- In your design, the hot-end has moved closer to the X-axis rods by 2.2mm
- The PINDA has moved closer to the X-axis rods by 2.15mm

**Comment by gregsaun** [comment]
Hi Panayiotis, thanks for helping me on this. Unfortunately, I have something quite different from my measurements :

X-Carriage MK2.5 from Prusa (STL imported) :
![x_carriage_prusa](https://user-images.githubusercontent.com/12335098/40536796-8e4c1108-600d-11e8-9d0a-b965d3e72698.png)

X-Carriage MK2.5 from Bear :
![x_carriage_bear](https://user-images.githubusercontent.com/12335098/40536815-9d3e5c3e-600d-11e8-83fc-bdfd38640164.jpg)

Pinda mount from Prusa (STL converted by [jzkmath](https://github.com/jzkmath/Original-Prusa-i3/)) :
![pinda_mount_prusa](https://user-images.githubusercontent.com/12335098/40537050-338d9d94-600e-11e8-9a1d-b83f078b667b.jpg)

Pinda mount from Bear :
![pinda_mount_bear](https://user-images.githubusercontent.com/12335098/40537061-392996b8-600e-11e8-868f-c5be8f4ccbf8.jpg)

So 1.5mm delta on X carriage, which means the Pinda mount should move by the same dimension

I will publish soon a fix with a better mount that helps for adjustment as well as maintenance and building.

**Comment by Panayiotis-git** [comment]
Ok, you are right about the distances. You are talking about differences with MK2.5 and I measure differences with MK3.

But, I think the difference comes from the X-carriage thickness.
MK3: 15mm (12mm from edge to the center of the rod)
MK2.5: 14mm (11mm from edge to the center of the rod)
Bear: 13.5mm (9.5mm from edge to the center of the rod)

So, the 1.5mm you measure is 11mm - 9.5mm.

**Comment by gregsaun** [comment]
Fixed in https://github.com/gregsaun/bear_extruder_and_x_axis/commit/f53affef560640b3b3778b92ea220dfee2910335
