### ISSUE TITLE
X carriage back hits z-top

### ISSUE THREAD

**Issue by Panayiotis-git** [gregsaun/bear_extruder_and_x_axis#9]
If the extruder is at the left-most or right-most positions and I increase the Z position, the x_carriage_back part hits the z-top parts.
And also, the filament spool holder, if z-axis moved to top.

**Comment by gregsaun** [comment]
Sorry for my late answer, could you show me a quick and dirty photo where it is touching exactly?

**Comment by Panayiotis-git** [comment]
Hi, sorry for the delayed answer, but I was not near the printer.

I have marked the problem area with a red circle. I'll try to take a photo, but it is a difficult shot.
![image](https://user-images.githubusercontent.com/32783577/42137571-24e6b89e-7d77-11e8-9bf3-24cfd14276fe.png)

**Comment by Panayiotis-git** [comment]
Ok, I managed to get the photos.

1st and 2nd are for the z tops.
![problem 1 - from left](https://user-images.githubusercontent.com/32783577/42137723-575a7ee8-7d7a-11e8-8bda-4318ff599c95.JPG)
![problem 1 - from top](https://user-images.githubusercontent.com/32783577/42137724-595cb26a-7d7a-11e8-9619-777ec039a774.JPG)

3rd is for the filament spool holder. In fact the holder touches the screw and the hits the orange plastic.
![problem 2](https://user-images.githubusercontent.com/32783577/42137725-5ae24ba4-7d7a-11e8-8c35-8c2c3c7c9e20.JPG)

**Comment by gregsaun** [comment]
Solved with new version published yesterday, thanks again @Panayiotis-git
